export const FETCH_TEXT_REQUEST = 'FETCH_TEXT_REQUEST';
export const FETCH_TEXT_SUCCESS = 'FETCH_TEXT_SUCCESS';
export const FETCH_TEXT_ERROR = 'FETCH_TEXT_ERROR';
export const FETCH_TEXT_FINAL = 'FETCH_TEXT_FINAL';